### ISSUE TITLE
Show orders table

### ISSUE THREAD

**Issue by ideasasylum** [podia/jessica-project#5]
We want to see the following information, and be able to refund paid orders.

Our payment provider is pretty flaky: refunds take 10 seconds to complete and fail 25% of the time. So we need to handle slow operations and potential API errors.

Because the refunds take so long, it would be ideal if I could refund these with AJAX so I can refund multiple orders without having to wait for page refreshes.

This page is also extremely slow when there are hundreds of orders, so let us know if you have any suggestions for how we could improve performance.

**Hint:** No CSS is required for this task, but some JavaScript is. Use whatever JavaScript approach you're most comfortable with.

Here's the mockup:

![image](https://user-images.githubusercontent.com/37838/76038835-e46d4e80-5f07-11ea-9af8-4d8903a77bed.png)

## Confirmation before refunding:

![image](https://user-images.githubusercontent.com/37838/76038869-fbac3c00-5f07-11ea-9298-602ac72b44c6.png)

## Don't let me click the Refund button more than once

![refund-wait](https://user-images.githubusercontent.com/37838/76039126-b3414e00-5f08-11ea-8d19-2cab82cde5ec.png)

## Update the UI when the refund is complete

![image](https://user-images.githubusercontent.com/37838/76039150-c0f6d380-5f08-11ea-85de-e788971fe414.png)

## Show me a simple alert if the refund fails

![image](https://user-images.githubusercontent.com/37838/76039263-1a5f0280-5f09-11ea-8a35-51adf18759ca.png)

**Comment by wafflewitch** [comment]
@ideasasylum I'm trying to use jQuery but I'm getting a console error that says `$ is not defined`. I've read through a few suggestions on StackOverflow but haven't found anything that works. Do you have any ideas?

**Comment by wafflewitch** [comment]
@ideasasylum  Nevermind, I worked around it!

**Comment by wafflewitch** [comment]
I'm 99% done and just fixing a bug now, but it's quite late so I'm going to sleep on it and figure it out in the morning.
